# Generated by Django 4.2.13 on 2024-10-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.BooleanField(default=False)),
                ('vegetable', models.BooleanField(default=False)),
                ('cannedGoods', models.BooleanField(default=False)),
                ('dairy', models.BooleanField(default=False)),
                ('meat', models.BooleanField(default=False)),
                ('seafood', models.BooleanField(default=False)),
                ('deli', models.BooleanField(default=False)),
                ('condiment', models.BooleanField(default=False)),
                ('snack', models.BooleanField(default=False)),
                ('bakery', models.BooleanField(default=False)),
                ('beverage', models.BooleanField(default=False)),
                ('carbohydrate', models.BooleanField(default=False)),
                ('frozen', models.BooleanField(default=False)),
                ('personal', models.BooleanField(default=False)),
                ('health', models.BooleanField(default=False)),
                ('clean', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('metric', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('L', 'Litre'), ('mL', 'MilliLitre'), ('gal', 'Gallon')], max_length=10)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.tags')),
            ],
        ),
    ]
