# Generated by Django 4.2.13 on 2024-10-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceries',
            name='item',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='metric',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('lb', 'Pound'), ('oz', 'Ounce'), ('L', 'Litre'), ('mL', 'MilliLitre'), ('gal', 'Gallon')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='groceries',
            name='quant',
            field=models.IntegerField(default=None),
        ),
    ]
